export const TECH_TAGS = [
  'cybersecurity',
  'infosec',
  'vulnerability',
  'exploit',
  'CVE',
  'malware',
  'ransomware',
  'XSS',
  'SQLi',
  'bug bounty',
  'zero-day',
  'linux',
  'docker',
  'kubernetes',
  'devops',
  'cloud',
  'AWS',
  'Azure',
  'python',
  'javascript',
  'go',
  'rust',
  'regex',
  'AI',
  'machine learning',
  'openai',
  'pen testing',
  'burp',
  'osint',
]

export const TAG_CATEGORIES = {
  SECURITY: [
    'cybersecurity',
    'infosec',
    'vulnerability',
    'exploit',
    'CVE',
    'malware',
    'ransomware',
    'XSS',
    'SQLi',
    'bug bounty',
    'zero-day',
    'pen testing',
    'burp',
    'osint',
  ],
  INFRASTRUCTURE: ['linux', 'docker', 'kubernetes', 'devops', 'cloud', 'AWS', 'Azure'],
  PROGRAMMING: ['python', 'javascript', 'go', 'rust', 'regex'],
  AI: ['AI', 'machine learning', 'openai'],
}

// Generate colors for each tag - bright hacker-themed colors
export const TAG_COLORS = [
  '#00ff00',
  '#00ff41',
  '#00ff82',
  '#00ffc3',
  '#00c3ff',
  '#0082ff',
  '#0041ff',
  '#0000ff',
  '#4100ff',
  '#8200ff',
  '#c300ff',
  '#ff00ff',
  '#ff00c3',
  '#ff0082',
  '#ff0041',
  '#ff4100',
  '#ff8200',
  '#ffc300',
  '#ffff00',
  '#c3ff00',
  '#82ff00',
  '#41ff00',
  '#00ff00',
  '#00ff20',
  '#00ff60',
  '#00ffa0',
  '#00ffe0',
  '#00e0ff',
  '#00a0ff',
  '#0060ff',
  '#0020ff',
]
